### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by tocute** [avishaycohen/mpd-parser#13]
Hi :
I just import this package.
I got this error "TypeError: 'type' object is not subscriptable"

was my step wrong ?

**Comment by avishaycohen** [comment]
hi, thanks for using the package, please if possible, can you add a snippet of the code you are running? and the traceback of the error message?

**Comment by avishaycohen** [comment]
also, if possible your python version, if you are using 3.8 and lower, you would get this error because of annotations I use to define some objects, you can see example in the code in `attribute_parsers.py` :
```python
def organize_ns(namespace_mapping: dict[Optional[str]]) -> dict:
```

**Comment by tocute** [comment]
thx for your reply quickly.

my python version is python3.10
and my code snippet  is from mpd_parser.parser import Parser

**Comment by avishaycohen** [comment]
can you please copy the stacktrace error?

**Comment by tocute** [comment]
sorry 
my python version is Python 3.8.9

`Traceback (most recent call last):
  File "a.py", line 1, in <module>
    from mpd_parser.parser import Parser
  File "/Users/bill/.local/share/virtualenvs/saku-api-smoke-test-TnUFtkjl/lib/python3.8/site-packages/mpd_parser/parser.py", line 8, in <module>
    from mpd_parser.tags import MPD
  File "/Users/bill/.local/share/virtualenvs/saku-api-smoke-test-TnUFtkjl/lib/python3.8/site-packages/mpd_parser/tags.py", line 12, in <module>
    from mpd_parser.attribute_parsers import get_text_value, organize_ns, get_float_value, get_bool_value, get_int_value, \
  File "/Users/bill/.local/share/virtualenvs/saku-api-smoke-test-TnUFtkjl/lib/python3.8/site-packages/mpd_parser/attribute_parsers.py", line 11, in <module>
    def organize_ns(namespace_mapping: dict[Optional[str]]) -> dict:
TypeError: 'type' object is not subscriptable`

**Comment by tocute** [comment]
thanks for your kind suggestion.
I'm in no hurry.
you can support to 3.8 when you have free time

thanks again

**Comment by avishaycohen** [comment]
new version is up, please install the new `0.1.0` either by uninstalling your current mpd-parser version
```
pip uninstal mpd-parser
pip install mpd-parser
```
or just upgrade:
`pip install mpd-parser -U`
