### ISSUE TITLE
SegmentTimeline.base_urls

### ISSUE THREAD

**Issue by wabiloo** [avishaycohen/mpd-parser#23]
**Describe the bug**
The SegmentTimeline object has a `base_urls` property with an array of Segment. https://github.com/avishaycohen/mpd-parser/blob/e0b0a4be9180be571be3216f1211413401210156/src/mpd_parser/tags.py#L569

That doesn't seem to be the right property name. `segments` surely?

**Setup**
1. 3.11
2. v0.1.2

**Expected behavior**
A name that better reflects the content of the property

**Actual behavior**
A misleading property name

**Comment by avishaycohen** [comment]
output after the fix using `manifests/aws-media-tailor-vod-personalized-response-manifest.mpd`
```
>>> parsed_mpd.periods[0].adaptation_sets[0].representations[0].segment_templates[0].segment_timelines[0].segments
[<mpd_parser.tags.Segment object at 0x7f7408beb510>, <mpd_parser.tags.Segment object at 0x7f7408beb190>]
>>> parsed_mpd.periods[0].adaptation_sets[0].representations[0].segment_templates[0].segment_timelines[0].segments[0]
<mpd_parser.tags.Segment object at 0x7f7408beb510>
>>> parsed_mpd.periods[0].adaptation_sets[0].representations[0].segment_templates[0].segment_timelines[0].segments[0].d
180000
>>> parsed_mpd.periods[0].adaptation_sets[0].representations[0].segment_templates[0].segment_timelines[0].segments[0].r
6
>>> parsed_mpd.periods[0].adaptation_sets[0].representations[0].segment_templates[0].segment_timelines[0].segments[0].t
0
>>> 
```
